// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzltrvukbtcbjzinotwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6bHRydnVrYnRjYmp6aW5vdHdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NzIwNzQsImV4cCI6MjA3NDM0ODA3NH0.HvkfM1eZKAZA1l_l_HuXG387XLt2kHqwoagBbuHCtQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});